using DevExpress.XtraEditors;
using System;
using System.Windows.Forms;
using weEnvanter.Business.Services.Interfaces;
using weEnvanter.Core.Helpers;

namespace weEnvanter.UI.Forms.EmployeeForms
{
    public partial class EmployeeListForm : DevExpress.XtraEditors.XtraForm
    {
        private readonly IEmployeeService _employeeService;

        public EmployeeListForm(IEmployeeService employeeService)
        {
            InitializeComponent();
            _employeeService = employeeService;
            // This line of code is generated by Data Source Configuration Wizard
            pLinqServerModeSource1.Source = new weEnvanter.Data.WeEnvanterDbContext().Employees;
            GridControlHelper.SetGridViewSettings(gridView_Employees);
            BarManagerHelper.SetBarManagerSettings(barManager1);
        }

        public void FilterByDepartment(int departmentId)
        {
            try
            {
                gridView_Employees.ActiveFilterString = $"[DepartmentId] = {departmentId}";
                gridView_Employees.ApplyColumnsFilter();
            }
            catch (Exception ex)
            {
                XtraMessageBox.Show($"Departman filtresi uygulanırken bir hata oluştu: {ex.Message}", 
                    "Hata", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
    }
}