using DevExpress.XtraEditors;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Windows.Forms;
using weEnvanter.Business.Services.Interfaces;
using weEnvanter.Core.Helpers;
using weEnvanter.Domain.Entities;
using weEnvanter.Domain.Enums;
using weEnvanter.UI.Forms.InventoryForms;
using DevExpress.XtraBars.ToastNotifications;
using static weEnvanter.Core.Helpers.ToastNotificationHelper;

namespace weEnvanter.UI.Forms.EmployeeForms
{
    public partial class EmployeeListForm : DevExpress.XtraEditors.XtraForm
    {
        private readonly IEmployeeService _employeeService;
        private readonly IInventoryService _inventoryService;
        private readonly ToastNotificationsManager _toastNotificationsManager;
        private readonly ISystemLogService _systemLogService;

        public EmployeeListForm()
        {
            InitializeComponent();
            _employeeService = Program.ServiceProvider.GetRequiredService<IEmployeeService>();
            _inventoryService = Program.ServiceProvider.GetRequiredService<IInventoryService>();
            _systemLogService = Program.ServiceProvider.GetRequiredService<ISystemLogService>();
            
            // Toast Notification Manager'ı başlat
            _toastNotificationsManager = ToastNotificationHelper.CreateManager(components);

            
            GridControlHelper.SetGridViewSettings(gridView_Employees);
            BarManagerHelper.SetBarManagerSettings(barManager1);
            LoadData();
        }
        private void LoadData()
        {
            // This line of code is generated by Data Source Configuration Wizard
            pLinqServerModeSource1.Source = new weEnvanter.Data.WeEnvanterDbContext().Employees;
        }
        public void FilterByDepartment(int departmentId)
        {
            try
            {
                gridView_Employees.ActiveFilterString = $"[DepartmentId] = {departmentId}";
                gridView_Employees.ApplyColumnsFilter();
            }
            catch (Exception ex)
            {
                _toastNotificationsManager.ShowError("Departman filtresi uygulanırken bir hata oluştu.");
            }
        }

        private void bar_RefreshDataSource_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                Cursor = Cursors.WaitCursor;
                pLinqServerModeSource1.Source = new weEnvanter.Data.WeEnvanterDbContext().Employees;
                pLinqServerModeSource1.Reload();
                _toastNotificationsManager.ShowSuccess("Veriler başarıyla yenilendi.");
            }
            catch (Exception ex)
            {
                _toastNotificationsManager.ShowError("Veriler yenilenirken bir hata oluştu.");
            }
            finally
            {
                Cursor = Cursors.Default;
            }
        }

        private void bar_ExportPDF_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                string userFullName = Program.CurrentUser != null ? $"{Program.CurrentUser.FirstName} {Program.CurrentUser.LastName}" : "Bilinmeyen Kullanıcı";
                string now = DateTime.Now.ToString("dd.MM.yyyy HH:mm");
                _systemLogService.LogActivity(
                    Program.CurrentUser?.Id,
                    "Çalışan Listesi PDF Dışa Aktarıldı",
                    $"{userFullName} {now} tarihinde çalışan listesini PDF olarak dışa aktardı.",
                    "Employee",
                    null,
                    weEnvanter.Domain.Enums.LogType.Information.ToString()
                );
                Core.Helpers.ExportHelper.ExportToPdf(gridControl_Employees, "weEnvanter_ÇalışanListesi");
            }
            catch (Exception ex)
            {
                XtraMessageBox.Show("PDF dışa aktarma sırasında bir hata oluştu: " + ex.Message, 
                    "Hata", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void bar_ExportXLSX_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                string userFullName = Program.CurrentUser != null ? $"{Program.CurrentUser.FirstName} {Program.CurrentUser.LastName}" : "Bilinmeyen Kullanıcı";
                string now = DateTime.Now.ToString("dd.MM.yyyy HH:mm");
                _systemLogService.LogActivity(
                    Program.CurrentUser?.Id,
                    "Çalışan Listesi Excel Dışa Aktarıldı",
                    $"{userFullName} {now} tarihinde çalışan listesini Excel olarak dışa aktardı.",
                    "Employee",
                    null,
                    weEnvanter.Domain.Enums.LogType.Information.ToString()
                );
                Core.Helpers.ExportHelper.ExportToExcel(gridControl_Employees, "weEnvanter_ÇalışanListesi");
            }
            catch (Exception ex)
            {
                XtraMessageBox.Show("Excel dışa aktarma sırasında bir hata oluştu: " + ex.Message, 
                    "Hata", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void bar_AddNewEmployee_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                using (var addEmployeeForm = new AddOrEditEmployeeForm(OperationType.Add))
                {
                    if (addEmployeeForm.ShowDialog() == DialogResult.OK)
                    {
                        pLinqServerModeSource1.Source = new weEnvanter.Data.WeEnvanterDbContext().Employees;
                        pLinqServerModeSource1.Reload();
                        _toastNotificationsManager.ShowSuccess("Çalışan başarıyla eklendi.");
                    }
                }
            }
            catch (Exception ex)
            {
                _toastNotificationsManager.ShowError("Çalışan eklenirken bir hata oluştu.");
            }
        }

        private void btn_EditEmployee_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            var selectedRow = gridView_Employees.GetFocusedRow() as Employee;
            if (selectedRow != null)
            {
                try
                {
                    using (var editForm = new AddOrEditEmployeeForm(OperationType.Update, selectedRow.Id))
                    {
                        if (editForm.ShowDialog() == DialogResult.OK)
                        {
                            pLinqServerModeSource1.Source = new weEnvanter.Data.WeEnvanterDbContext().Employees;
                            pLinqServerModeSource1.Reload();
                            _toastNotificationsManager.ShowSuccess("Çalışan başarıyla güncellendi.");
                        }
                    }
                }
                catch (Exception ex)
                {
                    _toastNotificationsManager.ShowError("Çalışan güncellenirken bir hata oluştu.");
                }
            }
        }

        private async void btn_DeleteEmployee_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            var selectedRow = gridView_Employees.GetFocusedRow() as Employee;
            if (selectedRow != null)
            {
                try
                {
                    bool canBeDeleted = await _employeeService.CanBeDeletedAsync(selectedRow.Id);
                    if (!canBeDeleted)
                    {
                        _toastNotificationsManager.ShowWarning("Bu çalışan silinemez. Zimmetli envanterleri olabilir.");
                        return;
                    }

                    if (XtraMessageBox.Show("Seçili çalışanı silmek istediğinize emin misiniz?", "Silme Onayı",
                        MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
                    {
                        await _employeeService.DeleteAsync(selectedRow.Id);
                        string userFullName = Program.CurrentUser != null ? $"{Program.CurrentUser.FirstName} {Program.CurrentUser.LastName}" : "Bilinmeyen Kullanıcı";
                        string now = DateTime.Now.ToString("dd.MM.yyyy HH:mm");
                        _systemLogService.LogActivity(
                            Program.CurrentUser?.Id,
                            "Çalışan Silindi",
                            $"{userFullName} {now} tarihinde '{selectedRow.FirstName} {selectedRow.LastName}' isimli çalışanı sildi.",
                            "Employee",
                            selectedRow.Id.ToString(),
                            weEnvanter.Domain.Enums.LogType.Information.ToString()
                        );
                        pLinqServerModeSource1.Reload();
                        _toastNotificationsManager.ShowSuccess("Çalışan başarıyla silindi.");
                    }
                }
                catch (Exception ex)
                {
                    _toastNotificationsManager.ShowError("Silme işlemi sırasında bir hata oluştu.");
                }
            }
        }

        private void btn_ShowEmbezzlement_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            var selectedRow = gridView_Employees.GetFocusedRow() as Employee;
            if (selectedRow != null)
            {
                try
                {
                    using (var inventoryListForm = new InventoryListForm())
                    {
                        // TODO: Burası da yapılacak.
                        //inventoryListForm.FilterByEmployee(selectedRow.Id);
                        inventoryListForm.ShowDialog();
                    }
                }
                catch (Exception ex)
                {
                    _toastNotificationsManager.ShowError("Zimmet listesi açılırken bir hata oluştu.");
                }
            }
        }

        private void btn_CreateEmbezzlementReport_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            var selectedRow = gridView_Employees.GetFocusedRow() as Employee;
            if (selectedRow != null)
            {
                try
                {
                    // TODO: Zimmet raporu oluşturma işlemi eklenecek
                    _toastNotificationsManager.ShowWarning("Bu özellik henüz eklenmedi.");
                }
                catch (Exception ex)
                {
                    _toastNotificationsManager.ShowError("Rapor oluşturulurken bir hata oluştu.");
                }
            }
        }

        private void gridView_Employees_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
            if(e.Button == MouseButtons.Right)
            {
                popupMenu1.ShowPopup(Cursor.Position);
            }
        }
    }
}