using DevExpress.XtraBars;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace weEnvanter.UI.Forms.Inventory
{
    public partial class InventoryListForm : DevExpress.XtraEditors.XtraForm
    {
        public InventoryListForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            pLinqServerModeSource1.Source = new weEnvanter.Data.WeEnvanterDbContext().Inventories;
        }
    }
}